### ISSUE TITLE
Organización de bibliotecas propensa a errores

### ISSUE THREAD

**Issue by sergio-ic** [ManuelDant/MoonPatrol#2]
No se recomienda tener las carpetas include y lib sueltas a la altura del resto.
Por el contrario, se sugiere que haya una única carpeta lib o libs y que dentro tenga subcarpetas por cada biblioteca de programación integrada. Entonces, por ejemplo, la estructura de su proyecto debería ser:

- base
--- src
--- res
--- libs
------raylib
---------- lib
---------- include

**Comment by ManuelDant** [comment]
Corregido la organización de bibliotecas.
